# Generated by Django 4.0.4 on 2022-05-17 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_staff_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(verbose_name=datetime.datetime(2022, 5, 17, 12, 38, 27, 356197, tzinfo=utc)),
        ),
    ]
