# Generated by Django 4.0.4 on 2022-05-17 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_staff_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
