# Generated by Django 4.0.4 on 2022-05-17 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_staff_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
