# Generated by Django 4.0.4 on 2022-05-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_staff_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.staff'),
        ),
        migrations.AlterField(
            model_name='client',
            name='staff_type',
            field=models.CharField(max_length=20),
        ),
    ]
