# Generated by Django 4.0.4 on 2022-05-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_client_staff_id_alter_client_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='staff_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
