# Generated by Django 4.0.4 on 2022-05-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_alter_client_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessaccount',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account', verbose_name='account_id'),
        ),
        migrations.AlterField(
            model_name='accessaccount',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client', verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='checkingaccount',
            name='account_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.account', verbose_name='account_id'),
        ),
        migrations.AlterField(
            model_name='clientloan',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client', verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='clientloan',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan', verbose_name='loan_id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client', verbose_name='client_id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.staff', verbose_name='leader_id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='subbranch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.subbranch', verbose_name='subbranch_name'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='subbranch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.subbranch', verbose_name='subbranch_name'),
        ),
        migrations.AlterField(
            model_name='payloan',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.loan', verbose_name='loan_id'),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.account', verbose_name='account_id'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.department', verbose_name='department_id'),
        ),
    ]
