# Generated by Django 4.0.4 on 2022-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_alter_accessaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('ap', 'account principal'), ('lp', 'loan principal')], max_length=20),
        ),
    ]
