# Generated by Django 4.0.4 on 2022-05-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_alter_client_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='leader_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.staff', verbose_name='leader_id'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subbranch',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
