# Generated by Django 4.0.4 on 2022-05-31 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('balanch', models.DecimalField(decimal_places=2, max_digits=20)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('staff_type', models.CharField(blank=True, choices=[('ap', 'account principal'), ('lp', 'loan principal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subbranch',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=64)),
                ('asset', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingAccount',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankSystem.account', verbose_name='account_id')),
                ('overdraft', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BankSystem.account', verbose_name='account_id')),
                ('currency_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.department', verbose_name='department_id')),
            ],
        ),
        migrations.CreateModel(
            name='PayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.loan', verbose_name='loan_id')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='subbranch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.subbranch', verbose_name='subbranch_name'),
        ),
        migrations.AddField(
            model_name='department',
            name='leader_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankSystem.staff', verbose_name='leader_id'),
        ),
        migrations.AddField(
            model_name='department',
            name='subbranch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.subbranch', verbose_name='subbranch_name'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('relation', models.CharField(max_length=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id')),
            ],
        ),
        migrations.CreateModel(
            name='ClientLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.loan', verbose_name='loan_id')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankSystem.staff', verbose_name='staff_id'),
        ),
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('least_recently_access', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.account', verbose_name='account_id')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payloan',
            constraint=models.UniqueConstraint(fields=('loan_id', 'pay_date'), name='PayLoan Primary Key'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('client_id', 'name'), name='Contact Primary key'),
        ),
        migrations.AddConstraint(
            model_name='clientloan',
            constraint=models.UniqueConstraint(fields=('loan_id', 'client_id'), name='ClientLoan Primary Key'),
        ),
        migrations.AddConstraint(
            model_name='accessaccount',
            constraint=models.UniqueConstraint(fields=('account_id', 'client_id'), name='AccessAccount Primary key'),
        ),
    ]
