# Generated by Django 4.0.4 on 2022-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('unissue', 'unissue'), ('issuing', 'issuing'), ('issued', 'issued')], default='issued', max_length=20),
        ),
    ]
