# Generated by Django 4.0.4 on 2022-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('account_principal', 'account principal'), ('loan_principal', 'loan principal')], max_length=20),
        ),
    ]
