# Generated by Django 4.0.4 on 2022-06-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0002_alter_client_staff_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accessaccount',
            table='AccessAccount',
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='checkingaccount',
            table='CheckingAccount',
        ),
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='clientloan',
            table='ClientLoan',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='Loan',
        ),
        migrations.AlterModelTable(
            name='payloan',
            table='PayLoan',
        ),
        migrations.AlterModelTable(
            name='savingsaccount',
            table='SavingsAccount',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
        migrations.AlterModelTable(
            name='subbranch',
            table='Subbranch',
        ),
    ]
