# Generated by Django 4.0.4 on 2022-06-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0003_rename_loan_amount_loan_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientloan',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='clientloan',
            old_name='loan_id',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='subbranch_name',
            new_name='subbranch',
        ),
        migrations.RenameField(
            model_name='payloan',
            old_name='loan_id',
            new_name='loan',
        ),
    ]
