# Generated by Django 4.0.4 on 2022-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0004_alter_client_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('account_principal', 'account principal'), ('loan_principal', 'loan principal')], default='account_principal', max_length=20),
        ),
    ]
