# Generated by Django 4.0.4 on 2022-06-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0004_rename_client_id_clientloan_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='lstatus',
            new_name='status',
        ),
    ]
