# Generated by Django 4.0.4 on 2022-06-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0006_alter_client_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id'),
        ),
    ]
