# Generated by Django 4.0.4 on 2022-06-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0007_alter_client_phone_alter_contact_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id'),
        ),
    ]
