# Generated by Django 4.0.4 on 2022-06-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankSystem', '0008_alter_contact_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubbranchClientAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('saving_account', 'saving_account'), ('loan_principal', 'loan principal')], max_length=20, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.client', verbose_name='client_id')),
                ('subbranch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankSystem.subbranch', verbose_name='subbranch_name')),
            ],
            options={
                'db_table': 'SubbranchClientAccountType',
            },
        ),
        migrations.AddConstraint(
            model_name='subbranchclientaccounttype',
            constraint=models.UniqueConstraint(fields=('subbranch_name', 'client_id', 'account_type'), name='SCAT Primary key'),
        ),
    ]
